// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbskftiteiysrofnpqrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ic2tmdGl0ZWl5c3JvZm5wcXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTg3MDcsImV4cCI6MjA2NDE3NDcwN30.P6TVCF3EuQ4gacq7lpAmyK2iGBx7tU8809Ts9YZWpPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);